alias gs='git status '
alias ga='git add '
alias gb='git for-each-ref --sort=-committerdate refs/heads/ --format="%(refname:short)"'
alias gc='git commit'
alias gd='git diff --'
alias gpom='git pull origin master'
alias gpum='git pull upstream master'
alias gl="git log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short"
alias glm="git log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short --author=jg@stripe.com"
alias go='git checkout '
alias goback='git checkout -'
alias gt='git tag '
alias gtype='git cat-file -t '
alias gdump='git cat-file -p '
alias grs='git reset --soft'
alias gmm='git merge master'
alias grm='git rebase master'
alias grom='git rebase origin/master'
alias gdm='git diff master'
alias gcaa='git commit -a --amend'
alias gcp='git commit -a -m cp'
alias grm='git fetch origin && git rebase origin/master'
alias gpoh='git push origin HEAD'
